spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/password_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

security:
  key: e5mHP0hbmgb9oduVPuPAnk27pU1swAS5